const routes = [
  { path: '/richfood-my-react/', element: <Home /> },
  { path: '/richfood-my-react/login', element: <LoginPage /> },
  { path: '/richfood-my-react/memberLogin', element: <MemberLoginPage /> },
  { path: '/richfood-my-react/memberRegister', element: <MemberRegister /> },
  { path: '/richfood-my-react/myRecommend', element: <MyRecommend /> },
  { path: '/richfood-my-react/paymentPage', element: <PaymentPage /> },
  { path: '/richfood-my-react/storeLogin', element: <StoreLoginPage /> },
  { path: '/richfood-my-react/systemManage', element: <SystemManage /> },
  { path: '/richfood-my-react/PopularPage', element: <PopularPage /> },
  { path: '/richfood-my-react/StoreQRCodeScanner', element: <StoreQRCodeScanner /> },
  { path: '/richfood-my-react/contactUs', element: <ContactUsPage /> },
  { path: '/richfood-my-react/StorePage/book', element: <BookPage /> },
  { path: '/richfood-my-react/book', element: <BookPage /> },
  { path: '/richfood-my-react/forgot-password', element: <ForgotPasswordPage /> },
  { path: '/richfood-my-react/reset-password', element: <ResetPasswordPage /> },
  { path: '/richfood-my-react/restaurant/:id', element: <RestaurantDetail /> },
  { path: '/richfood-my-react/search', element: <MySearchField /> },
  { path: '/richfood-my-react/profile', element: <MemberProfile /> },
  { path: '/richfood-my-react/comments', element: <Comments /> },
  { path: '/richfood-my-react/collections', element: <Collections /> },
  { path: '/richfood-my-react/coupons', element: <Coupons /> },
  { path: '/richfood-my-react/reservations', element: <Reservations /> },
  { path: '/richfood-my-react/use-coupon/:couponId', element: <UseCoupon /> },
  { path: '/richfood-my-react/Header', element: <Header /> },
  { path: '/richfood-my-react/Footer', element: <Footer /> },
  { path: '/richfood-my-react/HomePicture1', element: <HomePicture1 /> },
  { path: '/richfood-my-react/HomePicture2', element: <HomePicture2 /> },
  { path: '/richfood-my-react/HomePicture3', element: <HomePicture3 /> },
  { path: '/richfood-my-react/HomeHeroImage', element: <HomeHeroImage /> },
  { path: '/richfood-my-react/SearchStore', element: <SearchStore /> },
  { path: '/richfood-my-react/StorePage', element: <StorePage /> },
  { path: '/richfood-my-react/Test2', element: <Test2 /> },
  { path: '/richfood-my-react/Test3', element: <Test3 /> },
  { path: '/richfood-my-react/Test4', element: <Test4 /> },

  // 英文版  
  { path: "/richfood-my-react/HomeEnglish", element: <HomeEnglish /> },
  { path: "/richfood-my-react/HomeName1E", element: <HomeName1E /> },
  { path: "/richfood-my-react/HomeName2E", element: <HomeName2E /> },
  { path: "/richfood-my-react/HomeName3E", element: <HomeName3E /> },
  { path: "/richfood-my-react/HomePicture1E", element: <HomePicture1E /> },
  { path: "/richfood-my-react/HomePicture2E", element: <HomePicture2E /> },
  { path: "/richfood-my-react/HomePicture3E", element: <HomePicture3E /> },
  { path: "/richfood-my-react/HomeHeroImageE", element: <HomeHeroImageE /> }
];
